### ISSUE TITLE
Improve containers security in Kube

### ISSUE THREAD

**Issue by DCosti** [osstotalsoft/generator-webapp-rocket#22]
At this moment, applications that are generated using this template are running as a root in Kube. This is a security issue. In order to fix it, changes need to be done in docker file and helm:

1. Docker file changes: 
   - create an user
   - set as current user and make sure the application is running under this user
 2. Helm changes:
   - create an user
   - set as current user and make sure the application is running under this user
   - modify the port that the solution is listening. After user modification, the port must be greater than 1024

**Comment by alexandra-c** [comment]
Fixed
