### ISSUE TITLE
Debounce Should Not Be Active as Default

### ISSUE THREAD

**Issue by dragos-rosca** [osstotalsoft/generator-webapp-rocket#6]
https://github.com/osstotalsoft/generator-webapp-rocket/blob/9e830641891f715b8257176aeba038678e384ef1/generators/app/templates/infrastructure/src/components/common/inputs/CustomTextField.js#L124

The debounce functionality should be opt in not active by default

please set default to 0

**Comment by alexandra-c** [comment]
will be fixed in
#https://github.com/osstotalsoft/rocket-webapp-components/issues/3
